### environtment variables
@HOST = http://localhost:8080

#################################################################################### start of crud
### crud list
GET {{HOST}}/crud HTTP/1.1

### crud read
GET {{HOST}}/crud/1 HTTP/1.1

### crud create
POST {{HOST}}/crud HTTP/1.1
Content-Type: application/json

{
    "name": "nama todo"
}

### crud update partial
PATCH {{HOST}}/crud/1 HTTP/1.1
Content-Type: application/json

{
    "name": "update nama todo"
}

### crud update
PUT {{HOST}}/crud/1 HTTP/1.1
Content-Type: application/json

{
    "name": "update nama todo"
}

### crud delete
DELETE {{HOST}}/crud/1 HTTP/1.1
#################################################################################### end of crud

#################################################################################### start of content-types
### json response
GET {{HOST}}/content-types/json HTTP/1.1

### html response
GET {{HOST}}/content-types/html HTTP/1.1

### form request
POST {{HOST}}/content-types/form HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=kudanil

### json request, validation is route to test request body and validation library
POST {{HOST}}/content-types/validation HTTP/1.1
Content-Type: application/json

{
    "name": "a"
}
#################################################################################### end of content-types

#################################################################################### start of root
### graceful shutdown after send request we must kill the server with ctrl+c
GET {{HOST}}/graceful-shutdown HTTP/1.1


### reject is route to custom when request body is error
POST {{HOST}}/reject HTTP/1.1
Content-Type: application/json

{
    "key": ""
}
#################################################################################### end of root

#################################################################################### start default fallback
### not-found path is for testing that is no route path found in the server
#################################################################################### end default fallback
GET {{HOST}}/not-found HTTP/1.1